

team_mapping = {'kan':'KC',
                'min':'MIN',
                'det':'DET',
                'phi':'PHI',
                'den':'DEN',
                'atl':'ATL',
                'gnb':'GB',
                'buf':'BUF',
                'cle':'CLE',
                'lar':'LA',
                'ten':'TEN',
                'oak':'OAK',
                'lac':'LAC',
                'dal':'DAL',
                'pit':'PIT',
                'nor':'NO',
                'car':'CAR',
                'was':'WAS',
                'chi':'CHI',
                'ari':'ARI',
                'nyj':'NYJ',
                'nwe':'NE',
                'jac':'JAC',
                'sea':'SEA',
                'bal':'BAL',
                'nyg':'NYG',
                'hou':'HOU',
                'sfo':'SF',
                'ind':'IND',
                'cin':'CIN',
                'mia':'MIA',
                'tam':'TB',
                'stl':'STL', # team moved
                'sdg':'SD' # team moved
               }
